.\" Automatically generated by Pandoc 3.1.8
.\"
.TH "Promise.all" "JS" "March 12, 2023" "JavaScript" "JavaScript Reference Manual"
.SH NAME
Promise.all - Promise.all()
.SH SYNOPSIS
The \f[B]\f[CB]Promise.all()\f[B]\f[R] static method takes an iterable
of promises as input and returns a single \f[CR]Promise\f[R].
This returned promise fulfills when all of the input\[cq]s promises
fulfill (including when an empty iterable is passed), with an array of
the fulfillment values.
It rejects when any of the input\[cq]s promises rejects, with this first
rejection reason.
.SH SYNTAX
.IP
.EX
Promise.all(iterable)
.EE
.SS Parameters
.TP
\f[B]iterable\f[R]
An iterable (such as an \f[CR]Array\f[R]) of promises.
.SS Return value
A \f[CR]Promise\f[R] that is:
.IP \[bu] 2
\f[B]Already fulfilled\f[R], if the \f[CR]iterable\f[R] passed is empty.
.IP \[bu] 2
\f[B]Asynchronously fulfilled\f[R], when all the promises in the given
\f[CR]iterable\f[R] fulfill.
The fulfillment value is an array of fulfillment values, in the order of
the promises passed, regardless of completion order.
If the \f[CR]iterable\f[R] passed is non-empty but contains no pending
promises, the returned promise is still asynchronously (instead of
synchronously) fulfilled.
.IP \[bu] 2
\f[B]Asynchronously rejected\f[R], when any of the promises in the given
\f[CR]iterable\f[R] rejects.
The rejection reason is the rejection reason of the first promise that
was rejected.
.SH DESCRIPTION
The \f[CR]Promise.all()\f[R] method is one of the promise concurrency
methods.
It can be useful for aggregating the results of multiple promises.
It is typically used when there are multiple related asynchronous tasks
that the overall code relies on to work successfully \[em] all of whom
we want to fulfill before the code execution continues.
.PP
\f[CR]Promise.all()\f[R] will reject immediately upon \f[B]any\f[R] of
the input promises rejecting.
In comparison, the promise returned by \f[CR]Promise.allSettled()\f[R]
will wait for all input promises to complete, regardless of whether or
not one rejects.
Use \f[CR]allSettled()\f[R] if you need the final result of every
promise in the input iterable.
.SH EXAMPLES
.SS Using Promise.all()
\f[CR]Promise.all\f[R] waits for all fulfillments (or the first
rejection).
.IP
.EX
const p1 = Promise.resolve(3);
const p2 = 1337;
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve(\[dq]foo\[dq]);
  }, 100);
});

Promise.all([p1, p2, p3]).then((values) => {
  console.log(values); // [3, 1337, \[dq]foo\[dq]]
});
.EE
.PP
If the \f[CR]iterable\f[R] contains non-promise values, they will be
ignored, but still counted in the returned promise array value (if the
promise is fulfilled):
.IP
.EX
// All values are non-promises, so the returned promise gets fulfilled
const p = Promise.all([1, 2, 3]);
// The only input promise is already fulfilled,
// so the returned promise gets fulfilled
const p2 = Promise.all([1, 2, 3, Promise.resolve(444)]);
// One (and the only) input promise is rejected,
// so the returned promise gets rejected
const p3 = Promise.all([1, 2, 3, Promise.reject(555)]);

// Using setTimeout, we can execute code after the queue is empty
setTimeout(() => {
  console.log(p);
  console.log(p2);
  console.log(p3);
});

// Logs:
// Promise { <state>: \[dq]fulfilled\[dq], <value>: Array[3] }
// Promise { <state>: \[dq]fulfilled\[dq], <value>: Array[4] }
// Promise { <state>: \[dq]rejected\[dq], <reason>: 555 }
.EE
.SS Asynchronicity or synchronicity of Promise.all
This following example demonstrates the asynchronicity of
\f[CR]Promise.all\f[R] when a non-empty \f[CR]iterable\f[R] is passed:
.IP
.EX
// Passing an array of promises that are already resolved,
// to trigger Promise.all as soon as possible
const resolvedPromisesArray = [Promise.resolve(33), Promise.resolve(44)];

const p = Promise.all(resolvedPromisesArray);
// Immediately logging the value of p
console.log(p);

// Using setTimeout, we can execute code after the queue is empty
setTimeout(() => {
  console.log(\[dq]the queue is now empty\[dq]);
  console.log(p);
});

// Logs, in order:
// Promise { <state>: \[dq]pending\[dq] }
// the queue is now empty
// Promise { <state>: \[dq]fulfilled\[dq], <value>: Array[2] }
.EE
.PP
The same thing happens if \f[CR]Promise.all\f[R] rejects:
.IP
.EX
const mixedPromisesArray = [Promise.resolve(33), Promise.reject(44)];
const p = Promise.all(mixedPromisesArray);
console.log(p);
setTimeout(() => {
  console.log(\[dq]the queue is now empty\[dq]);
  console.log(p);
});

// Logs:
// Promise { <state>: \[dq]pending\[dq] }
// the queue is now empty
// Promise { <state>: \[dq]rejected\[dq], <reason>: 44 }
.EE
.PP
\f[CR]Promise.all\f[R] resolves synchronously if and only if the
\f[CR]iterable\f[R] passed is empty:
.IP
.EX
const p = Promise.all([]); // Will be immediately resolved
const p2 = Promise.all([1337, \[dq]hi\[dq]]); // Non-promise values are ignored, but the evaluation is done asynchronously
console.log(p);
console.log(p2);
setTimeout(() => {
  console.log(\[dq]the queue is now empty\[dq]);
  console.log(p2);
});

// Logs:
// Promise { <state>: \[dq]fulfilled\[dq], <value>: Array[0] }
// Promise { <state>: \[dq]pending\[dq] }
// the queue is now empty
// Promise { <state>: \[dq]fulfilled\[dq], <value>: Array[2] }
.EE
.SS Using Promise.all() with async functions
Within async functions, it\[cq]s very common to \[lq]over-await\[rq]
your code.
For example, given the following functions:
.IP
.EX
function promptForDishChoice() {
  return new Promise((resolve, reject) => {
    const dialog = document.createElement(\[dq]dialog\[dq]);
    dialog.innerHTML = \[ga]
<form method=\[dq]dialog\[dq]>
  <p>What would you like to eat?</p>
  <select>
    <option value=\[dq]pizza\[dq]>Pizza</option>
    <option value=\[dq]pasta\[dq]>Pasta</option>
    <option value=\[dq]salad\[dq]>Salad</option>
  </select>
  <menu>
    <li><button value=\[dq]cancel\[dq]>Cancel</button></li>
    <li><button type=\[dq]submit\[dq] value=\[dq]ok\[dq]>OK</button></li>
  </menu>
</form>
    \[ga];
    dialog.addEventListener(\[dq]close\[dq], () => {
      if (dialog.returnValue === \[dq]ok\[dq]) {
        resolve(dialog.querySelector(\[dq]select\[dq]).value);
      } else {
        reject(new Error(\[dq]User cancelled dialog\[dq]));
      }
    });
    document.body.appendChild(dialog);
    dialog.showModal();
  });
}

async function fetchPrices() {
  const response = await fetch(\[dq]/prices\[dq]);
  return await response.json();
}
.EE
.PP
You may write a function like this:
.PP
\f[B]Bad\f[R]
.IP
.EX
async function getPrice() {
  const choice = await promptForDishChoice();
  const prices = await fetchPrices();
  return prices[choice];
}
.EE
.PP
However, note that the execution of \f[CR]promptForDishChoice\f[R] and
\f[CR]fetchPrices\f[R] don\[cq]t depend on the result of each other.
While the user is choosing their dish, it\[cq]s fine for the prices to
be fetched in the background, but in the code above, the
\f[CR]await\f[R] operator causes the async function to pause until the
choice is made, and then again until the prices are fetched.
We can use \f[CR]Promise.all\f[R] to run them concurrently, so that the
user doesn\[cq]t have to wait for the prices to be fetched before the
result is given:
.PP
\f[B]Good\f[R]
.IP
.EX
async function getPrice() {
  const [choice, prices] = await Promise.all([
    promptForDishChoice(),
    fetchPrices(),
  ]);
  return prices[choice];
}
.EE
.PP
\f[CR]Promise.all\f[R] is the best choice of concurrency method here,
because error handling is intuitive \[em] if any of the promises reject,
the result is no longer available, so the whole \f[CR]await\f[R]
expression throws.
.PP
\f[CR]Promise.all\f[R] accepts an iterable of promises, so if you are
using it to parallelize execution of several async functions, you need
to call the async functions and use the returned promises.
Directly passing the functions to \f[CR]Promise.all\f[R] does not work,
since they are not promises.
.PP
\f[B]Bad\f[R]
.IP
.EX
async function getPrice() {
  const [choice, prices] = await Promise.all([
    promptForDishChoice,
    fetchPrices,
  ]);
  // \[ga]choice\[ga] and \[ga]prices\[ga] are still the original async functions;
  // Promise.all() does nothing to non-promises
}
.EE
.SS Promise.all fail-fast behavior
\f[CR]Promise.all\f[R] is rejected if any of the elements are rejected.
For example, if you pass in four promises that resolve after a timeout
and one promise that rejects immediately, then \f[CR]Promise.all\f[R]
will reject immediately.
.IP
.EX
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(\[dq]one\[dq]), 1000);
});
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(\[dq]two\[dq]), 2000);
});
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(\[dq]three\[dq]), 3000);
});
const p4 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(\[dq]four\[dq]), 4000);
});
const p5 = new Promise((resolve, reject) => {
  reject(new Error(\[dq]reject\[dq]));
});

// Using .catch:
Promise.all([p1, p2, p3, p4, p5])
  .then((values) => {
    console.log(values);
  })
  .catch((error) => {
    console.error(error.message);
  });

// Logs:
// \[dq]reject\[dq]
.EE
.PP
It is possible to change this behavior by handling possible rejections:
.IP
.EX
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => resolve(\[dq]p1_delayed_resolution\[dq]), 1000);
});

const p2 = new Promise((resolve, reject) => {
  reject(new Error(\[dq]p2_immediate_rejection\[dq]));
});

Promise.all([p1.catch((error) => error), p2.catch((error) => error)]).then(
  (values) => {
    console.log(values[0]); // \[dq]p1_delayed_resolution\[dq]
    console.error(values[1]); // \[dq]Error: p2_immediate_rejection\[dq]
  },
);
.EE
.SH SEE ALSO
.IP \[bu] 2
\f[CR]Promise\f[R]
.IP \[bu] 2
\f[CR]Promise.allSettled()\f[R]
.IP \[bu] 2
\f[CR]Promise.any()\f[R]
.IP \[bu] 2
\f[CR]Promise.race()\f[R]
